# This file was generated by GoReleaser. DO NOT EDIT.
cask "openshell-driver-applecontainer" do
  depends_on arch: :arm64

  version "0.2.8"

  on_macos do
    on_arm do
      sha256 "55d74addffda20c4abda9e01d3d80c3263c78084090e8943d6151506db3e4a27"
      url "https://github.com/vyncint/openshell-driver-applecontainer/releases/download/v#{version}/openshell-driver-applecontainer_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "openshell-driver-applecontainer"
  desc "OpenShell compute driver backed by apple/container micro-VMs"
  homepage "https://github.com/vyncint/openshell-driver-applecontainer"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "nvidia/openshell/openshell",
    ]

  binary "openshell-driver-applecontainer"

  postflight do
    staged = "#{staged_path}/openshell-driver-applecontainer"
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged]
    end
  end

  uninstall launchctl: [
      "local.openshell-driver-applecontainer",
    ]

  zap trash: [
      "~/.local/state/openshell-applecontainer",
      "~/Library/LaunchAgents/local.openshell-driver-applecontainer.plist",
      "~/Library/Logs/openshell-driver-applecontainer.log",
    ]

  caveats <<~EOS
    If OpenShell itself was not installed alongside this driver, install it
    by name so Homebrew taps NVIDIA's tap for you:

      brew install nvidia/openshell/openshell

    apple/container is required too, and is not available through Homebrew.
    Take it from https://github.com/apple/container/releases (signed .pkg).

    Then wire up the stack — launchd service, gateway configuration, vmnet
    network, images. Idempotent, so re-run it any time to repair:

      openshell-driver-applecontainer setup

    Re-run `setup` after every `brew upgrade` too: it restarts the launchd
    service onto the new binary.
  EOS
end
