# This file is generated by mossaic's release workflow. DO NOT EDIT.
# https://github.com/vyncint/mossaic/blob/main/.github/workflows/binaries.yml
class Mossaic < Formula
  desc "GitHub's contribution chart in your terminal, and a planner for contribution art"
  homepage "https://github.com/vyncint/mossaic"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/vyncint/mossaic/releases/download/v0.7.0/mossaic-0.7.0-aarch64-apple-darwin.tar.gz"
      sha256 "0caced57afb27ff3ea3559684ddc20c93f6097ea3a9830859f73ccf5891ccaa5"
    end
    on_intel do
      url "https://github.com/vyncint/mossaic/releases/download/v0.7.0/mossaic-0.7.0-x86_64-apple-darwin.tar.gz"
      sha256 "d9162ec8a62f35870a873fcd8194d06d5acef68490058dcc41341f319ad18b73"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyncint/mossaic/releases/download/v0.7.0/mossaic-0.7.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "28a483ea9ea6225d2482eaaf47955a2b1abcf71c711dd914602eec8d2eb18665"
    end
    on_intel do
      url "https://github.com/vyncint/mossaic/releases/download/v0.7.0/mossaic-0.7.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "fdc6e22a48d5962dca1db3222d40cdbf16a7049404c5972df35d9aa78b65048f"
    end
  end

  def install
    bin.install "mossaic", "mossaic-art", "mossaic-glyphs"
    doc.install "README.md", "CHANGELOG.md"
    # The templates are compiled into the binary; this copy is what
    # somebody starts from when drawing their own.
    pkgshare.install "templates"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mossaic-art --version")
    # The built-in catalogue survived packaging, which is the one thing
    # about this binary that a plain --version cannot show.
    assert_match "dragon", shell_output("#{bin}/mossaic-art --list-templates")
    # And it draws: no account, no network, no terminal.
    assert_match "2027", shell_output("#{bin}/mossaic-art --template dragon --year 2027 --no-color --plan /dev/null")
  end
end
