# This file is generated by mossaic's release workflow. DO NOT EDIT.
# https://github.com/vyncint/mossaic/blob/main/.github/workflows/binaries.yml
class Mossaic < Formula
  desc "GitHub's contribution chart in your terminal, and a planner for contribution art"
  homepage "https://github.com/vyncint/mossaic"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/vyncint/mossaic/releases/download/v0.8.0/mossaic-0.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "ca7c0ef8c93a22ce6f34f47f3384dc8b52187a2ffe4160cffcdf841522630e46"
    end
    on_intel do
      url "https://github.com/vyncint/mossaic/releases/download/v0.8.0/mossaic-0.8.0-x86_64-apple-darwin.tar.gz"
      sha256 "f234de74e1d5a5c5873814bc4092cff240d811b0bcfa4578402556751de1dd75"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyncint/mossaic/releases/download/v0.8.0/mossaic-0.8.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e3eef28aeda0cb0aa9a715a9499299fead2d81f4292deafdae5785cf18df34ec"
    end
    on_intel do
      url "https://github.com/vyncint/mossaic/releases/download/v0.8.0/mossaic-0.8.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "cd5270c9039028cfa84851d3f51ccda0edd72dde4f6cce0cb00319969d7aa736"
    end
  end

  def install
    bin.install "mossaic", "mossaic-art", "mossaic-glyphs"
    doc.install "README.md", "CHANGELOG.md"
    # The templates are compiled into the binary; this copy is what
    # somebody starts from when drawing their own.
    pkgshare.install "templates"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mossaic-art --version")
    # The built-in catalogue survived packaging, which is the one thing
    # about this binary that a plain --version cannot show.
    assert_match "dragon", shell_output("#{bin}/mossaic-art --list-templates")
    # And it draws: no account, no network, no terminal.
    assert_match "2027", shell_output("#{bin}/mossaic-art --template dragon --year 2027 --no-color --plan /dev/null")
  end
end
