# This file is generated by mossaic's release workflow. DO NOT EDIT.
# https://github.com/vyncint/mossaic/blob/main/.github/workflows/binaries.yml
class Mossaic < Formula
  desc "GitHub's contribution chart in your terminal, and a planner for contribution art"
  homepage "https://github.com/vyncint/mossaic"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/vyncint/mossaic/releases/download/v0.6.3/mossaic-0.6.3-aarch64-apple-darwin.tar.gz"
      sha256 "6715e557216b8d8fa45facd2e5e7854dca766d9075bfa075a2ce757051daead7"
    end
    on_intel do
      url "https://github.com/vyncint/mossaic/releases/download/v0.6.3/mossaic-0.6.3-x86_64-apple-darwin.tar.gz"
      sha256 "434f38938739f440f339a7b5e033a0eb2040bfd2a2b07d646e03a6c8b03c4d72"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyncint/mossaic/releases/download/v0.6.3/mossaic-0.6.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7b684acc7e0a35e578b4fa231cf22d520d439f5cc5d46796f51aee74fb9d2c5a"
    end
    on_intel do
      url "https://github.com/vyncint/mossaic/releases/download/v0.6.3/mossaic-0.6.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ea378a97706949fcbe408d5d21b8dc5905b8f5bb85b89430f80c047053f1d1a5"
    end
  end

  def install
    bin.install "mossaic", "mossaic-art", "mossaic-glyphs"
    doc.install "README.md", "CHANGELOG.md"
    # The templates are compiled into the binary; this copy is what
    # somebody starts from when drawing their own.
    pkgshare.install "templates"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mossaic-art --version")
    # The built-in catalogue survived packaging, which is the one thing
    # about this binary that a plain --version cannot show.
    assert_match "dragon", shell_output("#{bin}/mossaic-art --list-templates")
    # And it draws: no account, no network, no terminal.
    assert_match "2027", shell_output("#{bin}/mossaic-art --template dragon --year 2027 --no-color --plan /dev/null")
  end
end
