# This file is generated by oxidelake's release workflow. DO NOT EDIT.
# https://github.com/vyncint/oxidelake/blob/main/.github/workflows/binaries.yml
class Oxidelake < Formula
  desc "GPU-accelerated analytical engine on DataFusion and Ballista: SQL and vector search over Parquet"
  homepage "https://github.com/vyncint/oxidelake"
  license "Apache-2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.3/oxidelake-0.1.3-aarch64-apple-darwin.tar.gz"
      sha256 "58b851e8270607e365aba699f857a24bde79cc07082590b87d341e95b13efef5"
    end
    on_intel do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.3/oxidelake-0.1.3-x86_64-apple-darwin.tar.gz"
      sha256 "17ccbbbc23b32cf9d88596ed6fd13c660e539335e7353049eae69c058c7f122b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.3/oxidelake-0.1.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "f9e3301d61237e1726451bf46a143d2d9ad301b05fb63c66351ecb2ffc6fa574"
    end
    on_intel do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.3/oxidelake-0.1.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3771cd7eb0ef8574be55ecd741636b2096046e185919ad576f5f5a9e15425e96"
    end
  end

  def install
    bin.install "oxide", "oxide-scheduler", "oxide-worker"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oxide --version")
    # Generate a table and query it: the embedded engine works with no
    # cluster, no network and no GPU.
    system bin/"oxide", "gen-data", "--rows", "100", "--out", testpath/"data"
    out = shell_output("#{bin}/oxide sql -q \"SELECT count(*) AS n FROM t\" --table t=#{testpath}/data")
    assert_match "100", out
  end
end
