# This file is generated by oxidelake's release workflow. DO NOT EDIT.
# https://github.com/vyncint/oxidelake/blob/main/.github/workflows/binaries.yml
class Oxidelake < Formula
  desc "GPU-accelerated analytical engine on DataFusion and Ballista: SQL and vector search over Parquet"
  homepage "https://github.com/vyncint/oxidelake"
  license "Apache-2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.4/oxidelake-0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "557f501b08ae22229d5d2b2dc341ee0c093150e97485db85b216d9d9985b2d19"
    end
    on_intel do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.4/oxidelake-0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "87bf87a3afdba0403377ce376fcd5b8d81e80e4ddfd69cd29ec5146f9e8797b0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.4/oxidelake-0.1.4-aarch64-unknown-linux-musl.tar.gz"
      sha256 "1842c99604e9fc935361063545960609eac46a1caff95e56e1337b93e3b3a206"
    end
    on_intel do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.1.4/oxidelake-0.1.4-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2046addbf57dd6370a486ef026497edf98a2b56b94a1f1d91b8d58278f65ee1b"
    end
  end

  def install
    bin.install "oxide", "oxide-scheduler", "oxide-worker"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oxide --version")
    # Generate a table and query it: the embedded engine works with no
    # cluster, no network and no GPU.
    system bin/"oxide", "gen-data", "--rows", "100", "--out", testpath/"data"
    out = shell_output("#{bin}/oxide sql -q \"SELECT count(*) AS n FROM t\" --table t=#{testpath}/data")
    assert_match "100", out
  end
end
