# This file is generated by oxidelake's release workflow. DO NOT EDIT.
# https://github.com/vyncint/oxidelake/blob/main/.github/workflows/binaries.yml
class Oxidelake < Formula
  desc "GPU-accelerated analytical engine on DataFusion and Ballista: SQL and vector search over Parquet"
  homepage "https://github.com/vyncint/oxidelake"
  license "Apache-2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_arm do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.2.0/oxidelake-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "6ca1714affacdb84069ef518655892aea412d96dd47c0574a489602e46e388e6"
    end
    on_intel do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.2.0/oxidelake-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "381ff9c9700fa0518701f58836eb8f559090ccd0f5bbcf6ca6b96b136d3e30ba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.2.0/oxidelake-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "894fb5d3dc72fe0c84d957b7774985dca999ca66978992d4ad0fb9ddc0c6b48e"
    end
    on_intel do
      url "https://github.com/vyncint/oxidelake/releases/download/v0.2.0/oxidelake-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8ceaa3e5bc6fae133312c978509225ff5b89e6923a1d3a64220f8910cb947b60"
    end
  end

  def install
    bin.install "oxide", "oxide-scheduler", "oxide-worker"
    doc.install "README.md", "CHANGELOG.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/oxide --version")
    # Generate a table and query it: the embedded engine works with no
    # cluster, no network and no GPU.
    system bin/"oxide", "gen-data", "--rows", "100", "--out", testpath/"data"
    out = shell_output("#{bin}/oxide sql -q \"SELECT count(*) AS n FROM t\" --table t=#{testpath}/data")
    assert_match "100", out
  end
end
